// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q81HoHETamUnN6docDuBYG
import * as React from "react";
import { CmsCredentialsProvider } from "@plasmicpkgs/plasmic-cms"; // plasmic-import: OREVbGCcgN/codeComponent

export default function GlobalContextsProvider(props) {
  const { children, cmsCredentialsProviderProps } = props;
  return (
    <CmsCredentialsProvider
      {...cmsCredentialsProviderProps}
      databaseId={
        cmsCredentialsProviderProps &&
        "databaseId" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.databaseId
          : "Z61MPYkMPS1C7s5Gwphck"
      }
      databaseToken={
        cmsCredentialsProviderProps &&
        "databaseToken" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.databaseToken
          : "NAtLZQ3QlomV03TKOxKitD3skQavcrKOURT769UJkIFdfiSLVdupuYkdkSBsl5FFAF48lj679VZa5cfFdA"
      }
      host={
        cmsCredentialsProviderProps && "host" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.host
          : "https://studio.plasmic.app"
      }
      locale={
        cmsCredentialsProviderProps && "locale" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.locale
          : undefined
      }
    >
      {children}
    </CmsCredentialsProvider>
  );
}
